### ISSUE TITLE
Add lang class in title bar

### ISSUE THREAD

**Issue by kaileysnay** [s9e/phpbb-ext-highlighter#10]
If a lang is specified:
`[code lang=php]...[/code]`

It would be nice if the language was added in the title bar of the codebox. Example picture:
![php_code](https://user-images.githubusercontent.com/73230175/112089324-cc468c80-8b67-11eb-9832-dfeca41bf557.png)

**Comment by JoshyPHP** [comment]
I've looked into it but I don't think there's a proper way to do that at the extension level. Of course it's possible for the extension to modify the template but I don't want to add elements blindly. I thought about adding a `data-lang` attribute which could be used in CSS via `attr()` but that wouldn't be usable in your case.

I think it's better left to the style's `bbcode.html` to define its own template. The code's language is accessible via XPath using the `lang` attribute. For example, something like that would work:
```xsl
<xsl:if test="@lang">
    <b><xsl:value-of select="@lang"/></b>
</xsl:if>
```
