### ISSUE TITLE
Upgrade to v3.0.2 from v2.0.2 under phpBB 3.3.5 not working

### ISSUE THREAD

**Issue by Crizz0** [s9e/phpbb-ext-highlighter#11]
Hi,

i am using this highlighter in version 1.2.x and in 2.0.x. While 2.0.2 is working fine with the latest phpBB release 3.3.5, I cannot get the last version of this extension to work. So 3.0.2 does not highlight any text. I tried it with PHP and HTML.

**Comment by JoshyPHP** [comment]
Try completely uninstalling the old one, clear the caches then install the latest version. That works fine on my local 3.3.x board. If you don't see any highlighting, it's possible there's a JavaScript issue, or something with the markup used for your CODE tag. Do you see anything in your browser's console?

**Comment by Crizz0** [comment]
I did just use a freshly installed phpBB 3.3.5 which is used to test two language packages with prosilver standard. 

But the browser stops the loading of the JS:
> Die Ressource von "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.1.0/build/styles/github-gist.min.css" wurde wegen eines MIME-Typ-Konfliktes ("text/plain") blockiert (X-Content-Type-Options: nosniff) 

Maybe worth to add a IF-sentence, if this is not working, use a "included" JS file from highlightjs?

Edit: or the MS Edge tells me "Failed to load resource: the server responded with a status of 404 ()"

**Comment by JoshyPHP** [comment]
Ok I see, the latest release should be 3.0.3. I promoted the tag to a full GitHub release. This one should work better.

**Comment by Crizz0** [comment]
Okay, looks good with 3.0.3 now. 

Still the question, would it not be better to include the latest file into this extension? I would save the 3rd party connection from the board to the cdn, github etc.

**Comment by JoshyPHP** [comment]
That's a trade-off. The extension uses [hljs-loader](https://github.com/s9e/hljs-loader) so it doesn't have to bundle any files. Everything (loader, highlight.js and its stylesheet) is loaded from jsDelivr and the extension knows what versions of the files are the ~latest by checking up what versions are used by default in s9e\TextFormatter. That means you don't have to update any files on your side, including the extension's when things work right. I'm not entirely sure why 3.0.2 had to be updated but I'll take a look at it later.

**Comment by Crizz0** [comment]
I understand. But i thought of some kind of fallback included versions, for the cases the file loeader is not working. Would be of course more work for you, but maybe would be more stable for the operation.

**Comment by DrDeath** [comment]
...or working with intranets without accessing to the outer CDN world.

**Comment by JoshyPHP** [comment]
Yeah, it's just that I don't really want to invest more time maintaining this extension. I already keep hljs-loader in sync with highlight.js and I don't want to duplicate the work. If a motivated user wants to use it with their own files, all of the URLs are set as template variables so I assume it's possible to overwrite them in a custom style.

https://github.com/s9e/phpbb-ext-highlighter/blob/master/styles/all/template/event/overall_footer_body_after.html

Maybe with something like that, in their `overall_footer_body` template:
```twig
{% set s9e_highlighter_hljs_url         = '/path/to/highlight.js'   %}
{% set s9e_highlighter_script_src       = '/path/to/hljs-loader.js' %}
{% set s9e_highlighter_script_integrity = 'sha384-xxx'              %}
```
