### ISSUE TITLE
Include custom language - hints?

### ISSUE THREAD

**Issue by beinnlora** [s9e/phpbb-ext-highlighter#13]
Hello, I would like to include a custom language definition, but my knowledge of php is limited. 
Would you be able to give me some pointers please as to go about this? I have had a go, but am stuck.

I have created an extension to set the default language as per https://github.com/s9e/phpbb-ext-highlighter/issues/3#issuecomment-403817872

The extension also includes a script element to load 'mylanguage.js' in the header (or footer: I've tried both) as per https://highlightjs.org/#usage

But I receive:
WARN: Could not find the language 'mylanguage', did you forget to load/include a language module?

For my language definition, I have tried two formats of the mylanguage.js:
1) as per
https://github.com/highlightjs/highlight.js/blob/52370045327931058c2321eba7947c193427cab7/src/languages/basic.js
(editing and replacing for mylanguage.js). which returns in the console: 
"Uncaught SyntaxError: Unexpected token 'export'

2) and as per sample languages from highlight.js e.g.:
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/go.min.js
which returns in the console:
"Uncaught ReferenceError: hljs is not defined".

any hints greatly appreciated, thankyou

**Comment by JoshyPHP** [comment]
Sorry, I don't know anything about writing custom Highlight.js grammar files either.
