### ISSUE TITLE
phpbb-ext-highlighter mangles PHP code

### ISSUE THREAD

**Issue by amosbatto** [s9e/phpbb-ext-highlighter#2]
phpbb-ext-highlighter mangles PHP code and inserts line breaks in the code, making it unreadable. In phpBB3 3.2.2, see the screenshots of the PHP code with and without the highligher:

![phpwithouts9e](https://user-images.githubusercontent.com/4958913/41388447-7fd34d58-6f7b-11e8-8971-35b65858bef4.png)
![screwedupphpwiths9e](https://user-images.githubusercontent.com/4958913/41388449-80403850-6f7b-11e8-8b79-3e077bc48e3e.png)

**Comment by JoshyPHP** [comment]
Can you post the exact content of the original post in text form please? I need it to reproduce it locally.

**Comment by JoshyPHP** [comment]
It works fine for me and judging by those screenshots, this is an issue with your theme's CSS. Upgrade to the latest version of the add-on and make sure your theme does not define broad rules such as `code span`.
