### ISSUE TITLE
How to make default language C++?

### ISSUE THREAD

**Issue by Markox111** [s9e/phpbb-ext-highlighter#3]
Hello, how can i make the default language c++?

I tried to change style, find it in file init.min.js `styles/github-gist.min.css`

Can you explain also how this extension working? thanks.

**Comment by JoshyPHP** [comment]
That's not an option with this extension. There are many ways to do that if you want to [write your own extension](https://area51.phpbb.com/docs/dev/extensions/tutorial_bbcodes.html). For example, you can listen for the `core.text_formatter_s9e_parse_after` event and set `$event['parser']->get_parser()->tags['CODE']->attributes['lang']->defaultValue = 'cpp';`. Or you can use an event at rendering time and add the language attribute where applicable.

I don't think you need to do any of that though, in my experience Highlight.js correctly identifies C++ code and highlights it accordingly.

**Comment by Markox111** [comment]
I don't know in php, so why everytime i post any code it appears with only 1 style? I think it's php style

please check this photo: https://ibb.co/cnSKsT

should it automatically detect lanuage and highlights it right? or what shoult the right bbcode i must use? i used [code]javacode here[/code] javacode appear same as c++ same as all lanuages why?

**Comment by JoshyPHP** [comment]
I don't know whether it was highlighted as C++ or another language, since the name of the language only appears in the DOM. If it's not highlighted for the right language, you need to specify the language manually. The only way to force it to default to a given language is to make a phpBB extension for it.

**Comment by Markox111** [comment]
Even if i do like [code=cpp][/code] or [code=java][/code] it's same don't detect it, it assume all lanuages php.

I don't have experinece in php or web coding, can you give me your email you may write me one for my website and take money in return for this extension?

**Comment by JoshyPHP** [comment]
Sure. You can send me an email to phpwnd`＠`gmail.com with the specifications for the extension you want and I'll give you a quote.

While you're at it, send me the original code that's pictured in the image you posted earlier so I can see it for myself on my local board.

**Comment by Markox111** [comment]
Accept my conversation invite on gmail.

**Comment by JoshyPHP** [comment]
I don't know what a "conversation" is on GMail, did you mean GMail's chat? I'm rarely on GMail's site so it's better if you send me a regular email instead.

**Comment by Markox111** [comment]
Yes man, you will find me send you chat request you can accept it. Just check your gmail notifications :)
