### ISSUE TITLE
Add the option to enable line-numbers

### ISSUE THREAD

**Issue by Crizz0** [s9e/phpbb-ext-highlighter#6]
It would be a nice improvement, if there would be an option to display line numbers in the BBCode [code] element.

**Comment by JoshyPHP** [comment]
Doesn't look like it will happen: https://highlightjs.readthedocs.io/en/latest/line-numbers.html

**Comment by Crizz0** [comment]
Yeah, it looks like. 

Sometimes it would be nice to just say, see line 10 to 20, but you can just quote it, of course.

**Comment by JoshyPHP** [comment]
3D-I wrote a similar extension for Prism. There's a chance Prism has a plug-in for it.

https://github.com/phpBB-Studio/PrismSyntaxHighlighter

**Comment by Crizz0** [comment]
Yes, it does: https://prismjs.com/plugins/line-highlight/
