### ISSUE TITLE
loader.min.js and GDPR

### ISSUE THREAD

**Issue by ste101** [s9e/phpbb-ext-highlighter#7]
Because of the GDPR rules is would be better to include the loader.min.js into the EXT to load it localy.

**Comment by JoshyPHP** [comment]
I'd rather leave it to site owners to comply with all the applicable laws.

**Comment by ste101** [comment]
That's ok but loader.min.js is loaded from another domain so your plugin is not GDPR complicant by default.
Is there a special reason why you want to load loader.min.js from a CDN instead of loading it localy?

**Comment by JoshyPHP** [comment]
That's because the alternative is to bundle not just the loader but also the whole highlight.js library (which is currently loaded from the same CDN) and its nearly 200 files.
